version: '3'

services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - './backend:/srv/cap-emails/backend'
